name: Daily Job

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Para posibles pruebas manuales en el GitHub Action'
        required: false

jobs:
  run_job:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium openpyxl pandas jinja2

      - name: Run script
        run: python tableValoresyBolsa.py
