name: Daily Job

on:
  schedule:
    - cron: '0 18 * * 1-5'

jobs:
  run_job:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Si tienes un archivo de requisitos

      - name: Run script
        run: python tableValoresyBolsa.py