name: Keep Repository Active

on:
  schedule:
    - cron: '0 0 * * 0'  # This runs every Sunday at midnight

jobs:
  keep-active:
    runs-on: ubuntu-latest
    steps:
      - name: Check if it's the first Sunday of the month
        run: |
          day_of_month=$(date +%d)
          if [ "$day_of_month" -le 07 ]; then
            git config --global user.email "jczaragoza@hotmail.es"
            git config --global user.name "JuanquiZgz"
            git commit --allow-empty -m "Mantener actividad"
            git push
          else
            echo "No es el primer domingo del mes, no se realizará ningún commit."
        shell: bash
