name: Keep Repository Active

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
    inputs:
      message:
        description: 'Para posibles pruebas manuales en el GitHub Action'
        required: false

jobs:
  keep-active:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar archivos en el directorio scripts
        run: ls -la scripts

      - name: Configurar permisos del script
        run: chmod +x scripts/keep-active.sh

      - name: Ejecutar script para mantener el repositorio activo
        run: scripts/keep-active.sh



