name: Keep Repository Active

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
    inputs:
      message:
        description: 'Para posibles pruebas manuales en el GitHub Action'
        required: false

jobs:
  keep-active:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer un commit vacío solo si es el primer domingo del mes
        shell: bash
        run: |
          # Obtener el día del mes (1-31)
          day_of_month=$(date +%d)
          # Comprobar si es el primer domingo del mes (1-7)
          if [ "$day_of_month" -le 07 ]; then
            git config --global user.email "jczaragoza@hotmail.es"
            git config --global user.name "JuanquiZgz"
            git commit --allow-empty -m "Mantener actividad"
            git push
          else
            echo "No es el primer domingo del mes, no se realizará ningún commit."
