name: Keep Repository Active

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
    inputs:
      message:
        description: 'Para posibles pruebas manuales en el GitHub Action'
        required: false

jobs:
  keep-active:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }} # Usa el token de GitHub Actions

      - name: Configurar permisos del script
        run: chmod +x scripts/keep-active.sh

      - name: Ejecutar script de mantener activo
        run: ./scripts/keep-active.sh
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }} # Usa el token de GitHub Actions

